# Generated by Django 3.2.1 on 2021-05-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0003_auto_20210511_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='game',
            field=models.ManyToManyField(to='raterprojectapi.Game'),
        ),
        migrations.DeleteModel(
            name='GameCategory',
        ),
    ]
