# Generated by Django 3.2.1 on 2021-05-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0004_auto_20210511_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(related_name='games', to='raterprojectapi.Category'),
        ),
    ]
