# Generated by Django 3.2.1 on 2021-05-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0005_auto_20210512_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='reviews',
            field=models.ManyToManyField(related_name='reviews', to='raterprojectapi.Review'),
        ),
    ]
